### ISSUE TITLE
java.lang.IllegalArgumentException: Cannot translate null text

### ISSUE THREAD

**Issue by maiminhdung** [klxf/UniqueUUID#2]
[12:35:50 ERROR]: Error occurred while enabling UniqueUUID v1.2.0 (Is it up to date?)
java.lang.IllegalArgumentException: Cannot translate null text
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[commons-lang-2.6.jar:2.6]
        at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:355) ~[pearl-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at fang.uniqueuuid.Util.msgTranslate(Util.java:10) ~[UniqueUUID (1).jar:?]
        at fang.uniqueuuid.Util.getMessages(Util.java:17) ~[UniqueUUID (1).jar:?]
        at fang.uniqueuuid.UniqueUUID.onEnable(UniqueUUID.java:22) ~[UniqueUUID (1).jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[pearl-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[pearl-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:596) ~[pearl-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[pearl-1.18.2.jar:git-Pearl-"5cc23aa"]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[pearl-1.18.2.jar:git-Pearl-"5cc23aa"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:666) ~[pearl-1.18.2.jar:git-Pearl-"5cc23aa"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:433) ~[pearl-1.18.2.jar:git-Pearl-"5cc23aa"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:321) ~[pearl-1.18.2.jar:git-Pearl-"5cc23aa"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1166) ~[pearl-1.18.2.jar:git-Pearl-"5cc23aa"]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:317) ~[pearl-1.18.2.jar:git-Pearl-"5cc23aa"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[12:35:50 INFO]: [UniqueUUID] Disabling UniqueUUID v1.2.0
[12:35:50 INFO]: [UniqueUUID] ============ UniqueUUID ==============
[12:35:50 ERROR]: Error occurred while disabling UniqueUUID v1.2.0 (Is it up to date?)
java.lang.IllegalArgumentException: Cannot translate null text
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[commons-lang-2.6.jar:2.6]
        at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:355) ~[pearl-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at fang.uniqueuuid.Util.msgTranslate(Util.java:10) ~[UniqueUUID (1).jar:?]
        at fang.uniqueuuid.Util.getMessages(Util.java:17) ~[UniqueUUID (1).jar:?]
        at fang.uniqueuuid.UniqueUUID.onDisable(UniqueUUID.java:52) ~[UniqueUUID (1).jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[pearl-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:401) ~[pearl-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:633) ~[pearl-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:376) ~[pearl-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:596) ~[pearl-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[pearl-1.18.2.jar:git-Pearl-"5cc23aa"]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[pearl-1.18.2.jar:git-Pearl-"5cc23aa"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:666) ~[pearl-1.18.2.jar:git-Pearl-"5cc23aa"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:433) ~[pearl-1.18.2.jar:git-Pearl-"5cc23aa"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:321) ~[pearl-1.18.2.jar:git-Pearl-"5cc23aa"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1166) ~[pearl-1.18.2.jar:git-Pearl-"5cc23aa"]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:317) ~[pearl-1.18.2.jar:git-Pearl-"5cc23aa"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by klxf** [comment]
Fixed
